### PR TITLE
Add folder support for unzipped GTFS feeds.

### PR DESCRIPTION
**Pull request by danielsclint**
I have a need for supporting GTFS feeds unzipped. This change allows both zipped and folder based input for GTFS feed.

### CODE REVIEW

**Comment by danielsclint** [comment]
I just saw the note about linting. Let me run that real quick too.

**Comment by danielsclint** [comment]
I just saw the note about linting. Let me run that real quick too.

**Comment by danielsclint** [comment]
pep8 issues addressed.

**Comment by invisiblefunnel** [comment]
@danielsclint can you tell me about your use case for reading unzipped folders? I want to understand how partridge fits into your workflow before making this change.

**Comment by danielsclint** [comment]
I am helping a couple of MPOs with a dynamic transit simulation model. The project uses GTFS as the base for routing vehicles. The MPOs have added additional attributes to the GTFS feed such as vehicle capacity and vehicle acceleration profiles. The MPOs have added these attributes as additional files to the GTFS feed. 

Reading from an unzipped directory helps with debugging and it just saves a step in the setup procedures by not having to bundle up the files. We'll probably use Partridge regardless of whether this PR makes it way in, but this would help us align the workflow in our code with (what we hope) is a minor enhancement to the Partridge code base.

MPO Project Repo: https://github.com/BayAreaMetro/fast-trips/tree/develop
GTFS Simulation Add Ons: https://github.com/BayAreaMetro/fast-trips/tree/develop/fasttrips/Examples/test_scenario/network

**Comment by invisiblefunnel** [comment]
Thank you for the context @danielsclint. I'm generally in favor of this change. Two points of feedback on the PR as it is today:

1. The unzipping would ideally happen as part of test setup and teardown. Preferably with `ZipFile.extractall` and in a way that is abstracted away from the person writing the tests. Maybe a function called `fixture_folder` or similar.
1. Reducing duplication in the tests would make it more clear that the results should be identical whether reading from a zip or a folder. It would be ideal if the same test read from the zip and the unzipped folder then asserted equality.

Let me know if I can help. I might have some time to test out these ideas over the weekend.

**Comment by invisiblefunnel** [comment]
After reviewing https://github.com/BayAreaMetro/fast-trips/pull/111, I understand the conflicting workflows between partridge and fast-trips. Reading from directories makes sense to me and is something I'd like partridge to support.

@danielsclint @e-lo I'd be happy to publish a [pre-release version](https://packaging.python.org/tutorials/distributing-packages/#pre-release-versioning) of the package for you to depend on in fast-trips. That should unblock your work and give me time to polish this behavior. Can you rebase and update this branch?

**Comment by danielsclint** [comment]
I'll come back to this tomorrow afternoon, and modify the pull request.

**Comment by e-lo** [comment]
👍

**Comment by invisiblefunnel** [comment]
Closing in favor of #18

**Pull request closed without merging**
