### PR TITLE
Folder Support

### PR DESCRIPTION
**Pull request by danielsclint**
Here is a revised version of the PR to version 5.0 of Partridge. I changed around the implementation a little to keep your BufferedIO input to the pandas dataframe. I'm open to feedback on improving things.

I played around with a few different testing configurations, and this is the one that made the most sense to me. Again, please review and suggest changes.

Thanks.

### CODE REVIEW

**Comment by invisiblefunnel** [comment]
Neat! We'll take a closer look tomorrow and leave comments if we have any.

**Comment by e-lo** [comment]
@invisiblefunnel  - let us know if there is anything else we can do so that we can get a pre-release out there :-)

**Comment by invisiblefunnel** [comment]
Can you `rm -rf tests/fixtures/amazon-2017-08-06/__MACOSX/`? I can't comment directly on the file.

**Comment by invisiblefunnel** [comment]
Run `make lint`. I think there might some warnings to fix.

**Comment by danielsclint** [comment]
I removed the _MACOSX folder from the folder, but it is still in the matching zip. Since I didn't create the zip, I didn't want to remove it. It is probably just an artifact of the zip program used originally.

I also addressed the lint issues on the files I touched. There are still a fair number of docstrings that are needed across the project, but that seemed outside the scope of this PR and my knowledge of your code.

Thanks for working on this. Let me know if you want anymore changes.

**Comment by invisiblefunnel** [comment]
Thanks for all your work @danielsclint.

**Comment by invisiblefunnel** [comment]
This has been released as 0.6.0.dev1.

**Pull request merged**
