### PR TITLE
Python 2.7 Compatibility and Folder Input Enhancements

### PR DESCRIPTION
**Pull request by danielsclint**
I need to use Partridge in Python 2.7, so I made a few changes to fix the backport issues.

I also need to be able to read a folder with the GTFS files unzipped in addition to reading a zip file. This update now allows both folders and zip files to be read.

All of the tests and new tests pass in Python 2.7 and >3.5.

I hope this helps.

### CODE REVIEW

**Comment by invisiblefunnel** [comment]
@danielsclint these changes are very much appreciated! I'll have some time over the next few days to provide feedback/request minor changes. We should be able to get this merged and released soon.

**Comment by invisiblefunnel** [comment]
@danielsclint would you mind splitting this into two pull requests? One for py2.7 compatibility and one for folder-reading?

**Comment by invisiblefunnel** [comment]
Please also run `make lint` and correct any errors. Linting isn't currently part of the build, but I'd like it to be in the future. Thx.

**Comment by danielsclint** [comment]
The pull request has been split into 2 (#10 and #11). All tests pass and it has been run cleanly against flake8.

**Comment by invisiblefunnel** [comment]
Closing in favor of #10 and #11.

**Pull request closed without merging**
